Include 'rocksdb/util/crc32c_arm64.cc' on arm64 architectures
Level/rocksdb pull request #181
Opened 2021-09-21 14:54 UTC by Nazgolze

Closes #177 

Since this change is around cpu architecture and not OS, I did some testing on Ubuntu ARM64. Interestingly, 5.1.0 here did not have the same issue as on the Mac M1. Nevertheless, I've tested this PR on the M1 Mac and Ubuntu ARM64, have not encountered any errors and, so far, it's working well in our app (though the more eyeballs, the better - if @buu700 is able to give this a try as well :pray: )

2021-09-21 21:55 UTC, vweevers commented
Can we make this work for a universal binary as well? See https://github.com/Level/leveldown/pull/781 for comparison - I want to do the same for rocksdb

2021-09-24 14:12 UTC, vweevers requested changes

2021-09-24 14:12 UTC, vweevers commented on deps/rocksdb/rocksdb.gyp
> +            'rocksdb/util/crc32c_arm64.cc'
Can this `crc32c_arm64.cc` file be included unconditionally? By moving it to the main [sources](https://github.com/Level/rocksdb/blob/a54ad1e83782b600ffdfe3fa1bb142ae3e06a402/deps/rocksdb/rocksdb.gyp#L185).

The file has a [`#if defined(HAVE_ARM64_CRC)`](https://github.com/facebook/rocksdb/blob/09c7e96eac1ab983f97ce9e0406730b8014b3398/util/crc32c_arm64.cc#L8) so should already be a noop on other architectures.

2021-09-24 15:59 UTC, Nazgolze commented on deps/rocksdb/rocksdb.gyp
> +            'rocksdb/util/crc32c_arm64.cc'
I saw this just after I pushed just now :sweat_smile:
I'll have this in a sec :+1:

2021-09-24 16:04 UTC, Nazgolze commented on deps/rocksdb/rocksdb.gyp
> +            'rocksdb/util/crc32c_arm64.cc'
Pushed :+1:

2021-09-24 16:05 UTC, vweevers commented on binding.gyp
> +                    '-mmacosx-version-min=10.12'
Why 10.12?

2021-09-24 16:12 UTC, Nazgolze commented on binding.gyp
> +                    '-mmacosx-version-min=10.12'
I can change that back if desired :sweat_smile:
it was to match what was in `deps/rocksdb/rocksdb/build_tools/build_detect_platform`
but this was when I was debugging / testing

2021-09-24 16:26 UTC, vweevers commented on binding.gyp
> +                    '-mmacosx-version-min=10.12'
Let's keep it as-is here, to not make a breaking change.

2021-09-24 16:43 UTC, vweevers approved these changes
LGTM, thank you! Will release early next week

2021-09-24 16:47 UTC, vweevers commented
Note to self: on release, compare prebuild binary size to the previous release

2021-09-28 13:56 UTC, merged

2021-09-28 15:05 UTC, vweevers commented
5.1.1